cart/urls.py
from django.urls import path
from . import views

app_name = "cart"


urlpatterns = [
    path('cart/add/<uuid:id>/', views.cartadd, name='cartadd'),
    path('cart/item-clear/<uuid:id>/', views.itemclear, name='itemclear'),
    path('cart/cart-detail/',views.cartdetail, name='cartdetail'),

]

oasis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('pages.urls')),
    path('', include(('cart.urls', 'cart'), namespace='cart')),
    path('', RedirectView.as_view(url='pages/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/models.py
from django.db import models
import uuid # Required for unique listings
from django.forms import ModelForm
from django.urls import reverse
from pages.choices import *
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver


User = settings.AUTH_USER_MODEL




# Create your models here.

#class User(models.Model):
 #   email = models.EmailField(max_length=200)
 #   def __str__(self):
 #       return self.name


class Listing(models.Model):
    #fields
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='unique id for this listing')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User,
                        default = 1,
                        null = True,
                        on_delete = models.SET_NULL
                        )
    price= models.DecimalField(max_digits=10, decimal_places=2)
    hide_listing = models.BooleanField(default=False)
    times_reported = models.SmallIntegerField(default=0)
    report = models.ForeignKey('ReportListing',null = True, on_delete = models.SET_NULL)

    # not yet sure how users work - may want users not to be a model and instead use django default user handling
    # posted_by = models.ForeignKey('User', on_delete=models.SET_NULL,null=True)


    condition = models.CharField(
        max_length=1,
        choices=CONDITION,
        blank=True,
        default=1,
        help_text='Book condition',
    )
    # not yet sure yet how to handle images
    # image =

    class Meta:
        ordering = ['-date_added']

    # Methods
    def get_absolute_url(self):
        """Returns the url to access a particular instance of MyModelName."""
        return reverse('listings-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return f'{self.id} ({self.book.title})'

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    #if we decide to have a model for author:
    #author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    isbn = models.CharField('ISBN', max_length=13, unique=True, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    edition = models.CharField(max_length=5) #length here assumes no more than 999th edition -- seems like a reasonable assumption
    pub_year = models.SmallIntegerField()

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])


#message thread
class Conversation(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='unique id for this conversation')
    seller = models.ForeignKey(User,
                        related_name='seller',
                        default = 1,
                        null = True,
                        on_delete = models.SET_NULL
                        )
    buyer = models.ForeignKey(User,
                        related_name='buyer',
                        default = 2,
                        null = True,
                        on_delete = models.SET_NULL
            )
    report = models.ForeignKey('ReportListing',null = True, on_delete = models.SET_NULL)
    state = models.CharField(
        max_length=1,
        choices=STATUS,
        blank=True,
        default=0,
        help_text='Conversation status',
    )
    listing = models.ForeignKey(Listing, null = True, on_delete = models.SET_NULL)


class Message(models.Model):
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    sentby = models.ForeignKey(User,
                        default = 1,
                        null = True,
                        on_delete = models.SET_NULL
                        )
    conversation = models.ForeignKey(Conversation, default = 1, null=True, on_delete = models.SET_NULL)
    class Meta:
        ordering = ['-timestamp']

class ReportListing(models.Model):
    sent_by = models.ForeignKey(User, default = 1,
                        null = True,
                        on_delete = models.SET_NULL)
    date_reported = models.DateTimeField(auto_now_add=True)

class NumSearch(models.Model):
    count = models.IntegerField(default=0)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    buyer_rating = models.IntegerField(
        choices = RATINGS,
        default = 5,
    )
    seller_rating = models.IntegerField(
        choices = RATINGS,
        default = 5,
    )

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Photo(models.Model):
    uuid = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False,
    )
    created_at = models.DateTimeField(auto_now_add=True) 
    title = models.CharField(max_length=100)
    photo = models.FileField()

pages/templates/LandingPage.html
<!DOCTYPE html>
<html>
  <head>
    <title>Desktop Version</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <link href="resources/css/axure_rp_page.css" type="text/css" rel="stylesheet"/>
    <link href="data/styles.css" type="text/css" rel="stylesheet"/>
    <link href="files/desktop_version/styles.css" type="text/css" rel="stylesheet"/>
    <script src="resources/scripts/jquery-3.2.1.min.js"></script>
    <script src="resources/scripts/axure/axQuery.js"></script>
    <script src="resources/scripts/axure/globals.js"></script>
    <script src="resources/scripts/axutils.js"></script>
    <script src="resources/scripts/axure/annotation.js"></script>
    <script src="resources/scripts/axure/axQuery.std.js"></script>
    <script src="resources/scripts/axure/doc.js"></script>
    <script src="resources/scripts/messagecenter.js"></script>
    <script src="resources/scripts/axure/events.js"></script>
    <script src="resources/scripts/axure/recording.js"></script>
    <script src="resources/scripts/axure/action.js"></script>
    <script src="resources/scripts/axure/expr.js"></script>
    <script src="resources/scripts/axure/geometry.js"></script>
    <script src="resources/scripts/axure/flyout.js"></script>
    <script src="resources/scripts/axure/model.js"></script>
    <script src="resources/scripts/axure/repeater.js"></script>
    <script src="resources/scripts/axure/sto.js"></script>
    <script src="resources/scripts/axure/utils.temp.js"></script>
    <script src="resources/scripts/axure/variables.js"></script>
    <script src="resources/scripts/axure/drag.js"></script>
    <script src="resources/scripts/axure/move.js"></script>
    <script src="resources/scripts/axure/visibility.js"></script>
    <script src="resources/scripts/axure/style.js"></script>
    <script src="resources/scripts/axure/adaptive.js"></script>
    <script src="resources/scripts/axure/tree.js"></script>
    <script src="resources/scripts/axure/init.temp.js"></script>
    <script src="resources/scripts/axure/legacy.js"></script>
    <script src="resources/scripts/axure/viewer.js"></script>
    <script src="resources/scripts/axure/math.js"></script>
    <script src="resources/scripts/axure/jquery.nicescroll.min.js"></script>
    <script src="data/document.js"></script>
    <script src="files/desktop_version/data.js"></script>
    <script type="text/javascript">
      $axure.utils.getTransparentGifPath = function() { return 'resources/images/transparent.gif'; };
      $axure.utils.getOtherPath = function() { return 'resources/Other.html'; };
      $axure.utils.getReloadPath = function() { return 'resources/reload.html'; };
    </script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
  </head>
  <body>

    <!-- Navbar header -->
    <nav class="navbar navbar-expand-lg navbar-light text-white" style="background-color: #8a100b;">
          <a href="#" class="navbar-brand">
              <img src="images/desktop_version/u2.png" style="width: 60px;">
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-between text-center" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                  <a class="nav-link text-white dropdown-toggle" href="#" id="buyerdropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    BUYER SERVICES
                  </a>
                  <div class="dropdown-menu" aria-labelledby="buyerdropdown">
                    <a class="dropdown-item" href="#">VIEW MARKETPLACE</a>
                    <a class="dropdown-item" href="#">ADVANCED SEARCH</a>
                    <a class="dropdown-item" href="#">WISHLIST</a>
                    <a class="dropdown-item" href="">PURCHASE HISTORY</a>
                  </div>
              </li>
              <li class="nav-item dropdown">
                  <a class="nav-link text-white dropdown-toggle" href="#" id="admindropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    SELLER SERVICES
                  </a>
                  <div class="dropdown-menu" aria-labelledby="admindropdown">
                    <a class="dropdown-item" href="#">VIEW CURRENT BOOKS</a>
                    <a class="dropdown-item" href="#">COMPARE PRICES</a>
                    <a class="dropdown-item" href="#">SALE HISTORY</a>
                  </div>
              </li>
            </ul>
            <ul class="navbar-nav">
              <li class="nav-item">
                  <a class="nav-link text-white" href=""><i class="fa fa-shopping-cart"></i></a>
              </li>
              <li class="nav-item text-white dropdown">
                  <a class="nav-link text-white dropdown-toggle" href="#" id="profiledrop" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-user"></i>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right text-right" aria-labelledby="profiledrop">
                    <a class="dropdown-item" href="#">ACCOUNT SETTINGS</a>
                    <a class="dropdown-item" href="messaging.html">MESSAGES</a>
                    <a class="dropdown-item" href="#">WISHLIST</a>
                    <a class="dropdown-item" href="#">SIGN OUT</a>
                  </div>
              </li>
            </ul>
          </div>
      </nav>

    <div id="base" class="">

      <!-- textured white background left side  -->
      <div id="u0" class="ax_default image">
        <img id="u0_img" class="img " src="images/desktop_version/u0.png"/>
        <div id="u0_text" class="text " style="display:none; visibility: hidden">
          <p></p>
        </div>
      </div>

      <!-- gold background white side -->
      <div id="u1" class="ax_default box_2">
        <div id="u1_div" class=""></div>
        <div id="u1_text" class="text " style="display:none; visibility: hidden">
          <p></p>
        </div>
      </div>

      <!-- big bb logo -->
      <div id="u2" class="ax_default image">
        <img id="u2_img" class="img " src="images/desktop_version/u2.png"/>
        <div id="u2_text" class="text " style="display:none; visibility: hidden">
          <p></p>
        </div>
      </div>

      <!-- Book Bargains text left side -->
      <div id="u3" class="ax_default heading_1">
        <div id="u3_div" class=""></div>
        <div id="u3_text" class="text ">
          <p><span>Book Bargains</span></p>
        </div>
      </div>

      <!-- info text left side -->
      <div id="u4" class="ax_default heading_2">
        <div id="u4_div" class=""></div>
        <div id="u4_text" class="text ">
          <p><span>Join a community of college students</span></p><p><span>exchanging books at discounted prices</span></p>
        </div>
      </div>

      <!-- info text right side -->
      <div id="u5" class="ax_default heading_1">
        <div id="u5_div" class=""></div>
        <div id="u5_text" class="text ">
          <p><span style="font-family:'Arial-BoldMT', 'Arial Bold', 'Arial', sans-serif;font-style:normal;">Welcome to the </span><span style="font-family:'Arial-BoldItalicMT', 'Arial Bold Italic', 'Arial', sans-serif;font-style:italic;">best</span><span style="font-family:'Arial-BoldMT', 'Arial Bold', 'Arial', sans-serif;font-style:normal;"> university</span></p><p><span style="font-family:'Arial-BoldMT', 'Arial Bold', 'Arial', sans-serif;font-style:normal;">book exchange community!</span></p>
        </div>
      </div>

      <!-- Log in button-->
      <a href="test.com">
        <div id="u6" class="ax_default button">
          <div id="u6_div" class=""></div>
          <div id="u6_text" class="text ">
            <p><center>Log In</center></p>
          </div>
        </div>
      </a>

      <!-- Create account button-->
      <a href="test.com">
        <div id="u7" class="ax_default button">
          <div id="u7_div" class=""></div>
          <div id="u7_text" class="text ">
            <p><center>Create Account</center></p>
          </div>
        </div>
      </a>

      <!-- Unnamed (Rectangle) -->
      <div id="u8" class="ax_default heading_1">
        <div id="u8_div" class=""></div>
        <div id="u8_text" class="text " style="display:none; visibility: hidden">
          <p></p>
        </div>
      </div>

      <!-- text -->
      <div id="u9" class="ax_default heading_2">
        <div id="u9_div" class=""></div>
        <div id="u9_text" class="text ">
          <p><span>Are you…</span></p>
        </div>
      </div>

      <!-- buying button-->
      <a href="test.com">
        <div id="u10" class="ax_default primary_button">
            <div id="u10_div" class=""></div>
            <div id="u10_text" class="text ">
              <p><center>Buying</center></p>
            </div>
        </div>
      </a>

      <!-- selling button-->
      <a href="test.com">
        <div id="u11" class="ax_default primary_button">
          <div id="u11_div" class=""></div>
          <div id="u11_text" class="text ">
            <p><center>Selling</center></p>
          </div>
        </div>
      </a>

      <!-- info text right side -->
      <div id="u12" class="ax_default heading_3">
        <div id="u12_div" class=""></div>
        <div id="u12_text" class="text ">
          <p><span>Get books at discounted prices</span></p>
        </div>
      </div>

      <!-- info text right side  -->
      <div id="u13" class="ax_default heading_3">
        <div id="u13_div" class=""></div>
        <div id="u13_text" class="text ">
          <p><span>Sell unwanted books with ease</span></p>
        </div>
      </div>
    </div>
    <script src="resources/scripts/axure/ios.js"></script>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

pages/templates/listings_detail_view.html
{% extends "base.html" %}

{% block content %}
<div class="col-lg-10 col-md-10 col-sm-12 mx-auto my-5">
    <div class="row">
        <div id="imageSection" class="col-lg-4 col-md-4 mx-2" style="min-height: 100px;">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img class="d-block w-100" src="" alt="First slide">
                  </div>
                  <div class="carousel-item">
                    <img class="d-block w-100" src="" alt="Second slide">
                  </div>
                  <div class="carousel-item">
                    <img class="d-block w-100" src="" alt="Third slide">
                  </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
        </div>
        <div id="bookInfoSection" class="col-lg-4 col-md-4">
            <h1>{{ object.book.title }}</h1>
            <p><strong>Author:</strong> <a href="">{{ object.book.author }}</a></p> <!-- author detail link not yet defined -->
            
            
            <p><strong>ISBN:</strong> {{ object.book.isbn }}</p>
            <p><strong>Condition:</strong> {{ object.get_condition_display }}</p>
            <p><strong>Publishing Year:</strong> {{ object.book.pub_year }} </p>
            <p><strong>Edition:</strong> {{ object.book.edition }} </p>
            <p><strong>Price:</strong> ${{ object.price }} </p>
            <p><strong>Posted by: </strong> {{ object.user.username }} on {{ object.date_added }}</p>
        </div>
        <div id="actionsSection" class="col-lg-2 col-md-2 col-sm-2 my-auto">
            <a href="{% url 'cart:cartadd' object.id%}" class="btn btn-primary my-2 mx-auto">Add To Cart</a>
            <!-- <a href="{% url 'reportlisting' object.id %}" class="btn btn-primary my-2 mx-auto">Report Listing</a> -->
        </div>
    </div>
    
    
    
</div>



    <a href="{% url 'reportlisting' object.id %}" class="btn btn-primary">Report Listing</a>
	
	<br/>
	<br/>


    <!-- <div style="margin-left:20px;margin-top:20px"> -->
        <!-- <h4>Copies</h4> -->

        <!-- {% for copy in object.objectinstance_set.all %}
        <hr>
        <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
            {{ copy.get_status_display }}
        </p>
        {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
        {% endif %}
        <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
        <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
        {% endfor %} -->
        <!-- </div> -->
        {% endblock %}

pages/templates/listings_view.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<!-- <h1>All Listings ({{ object_list|length }})</h1> -->

<div class="text-center">
  <h1>Search Results</h1>
</div>

<div class="row">
  <div class="col-12 col-lg-12 py-2 mx-auto">
    <form class="form-inline justify-content-center">
      <!-- <form name="search" method="GET" action="{% url 'listings' %}"> 
        <input type="text" name="q" placeholder="Search"/>
        <button class="btn btn-primary " type="submit">Search</button>
      </form> -->
    </form>
  </div>
</div>

<div class="row">
  <div class="col-12 col-lg-12 py-2 mx-auto">
    <form class="form-inline justify-content-center">
      <!-- <form name="search" method="GET" action="{% url 'listings' %}"> 
        <input type="text" name="q" placeholder="Search"/>
        <button class="btn btn-primary " type="submit">Search</button>
      </form> -->
    </form>
  </div>
</div>

<div class="row mx-auto">
  <div class="col-lg-2 ml-2 py-2 my-2">
    <button class="btn-lg btn-primary mb-2 w-100" type="button" data-toggle="collapse" data-target="#conditions" aria-expanded="false" aria-controls="collapseExample">
      Filters
    </button>
      <div class="collapse" id="conditions">
        <form >

          {{ form.condition_field | as_crispy_field }}
          {{ form.title_field | as_crispy_field }}
          {{ form.author_field | as_crispy_field}}
          {{ form.edition_field | as_crispy_field }}

          <input type="submit" class="btn btn-primary" value="Apply">
        </form>
      </div>


    </form>
  </div>
  {% if object_list %}
  <div class="col-lg-9 col-md-10 col-sm-12 mx-auto">
    <form method='get' action='#'>
      <input class="btn btn-primary" type="submit" value="Price: Low to High" name="Price: Low to High"/>
    </form>
    
    {% for object in object_list %}
    {% if object.hide_listing is False %}
    <!-- will need to adjust to create grid with fixed num of columns  -->
    <!-- <div class="col-sm-4"> -->
      <!-- <a href="{{ object.get_absolute_url }}">{{ object.book.title }}</a> {{object.book.author}} -->
      <div class="row border rounded mb-3 py-1" style="min-height: 200px;">
        
        <div class="col-lg-2 col-md-2 col-sm-12 mx-2 my-auto" style="min-height: 50px;">
          Cover image of the book
        </div>
        
        <div class="col-lg-4 col-md-5 col-sm-12 my-auto mr-auto">
          <a class="text-decoration-none text-dark" href="{{ object.get_absolute_url }}" ><h4> {{ object.book.title }}</h4></a>
          <p class="text-muted"> {{ object.book.author }}</p>
          <p><strong>Edition:</strong> {{ object.book.edition }}</p>
          <p><strong>ISBN-13:</strong> {{ object.book.isbn }}</p>
          <p><strong>Sold by:</strong> {{ object.user.username }} </p>
        </div>
        
        <div class="my-auto col-lg-4 col-md-3 col-sm-12">
          <p><strong>Condition:</strong> {{object.get_condition_display}}</p> 
          <p><strong>Price:</strong> ${{ object.price}}</p>
          <a href="{{ object.get_absolute_url }}" class="btn btn-primary w-100 mb-3">Details</a>
        </div>
        
      </div>
      {% endif %}
      {% endfor %}
    </div>
  </div>
  
  <!-- <ul>
    {% for object in object_list %}
    <li>
      <a href="{{ object.get_absolute_url }}">{{ object.book.title }}</a> {{object.book.author}}
    </li>
    {% endfor %}
  </ul> -->
  {% else %}
  <p>There are no current listings.</p>
  {% endif %} 
</div>
{% endblock %}

pages/templates/profile.html
{% extends 'base.html' %}

{%block content%}
<div class="col-lg-10 col-md-11 col-sm-12 mx-auto">
	{% if user.is_authenticated %}

		<h1 class="text-center my-3">Welcome to your profile, {{user.username}}!</h1>

		<div class="text-center my-3">
			<p class="mb-2"><strong>Buyer Rating:</strong> {{user.profile.buyer_rating}}</p>
			<p><strong>Seller Rating:</strong> {{user.profile.seller_rating}}</p>
		</div>
		<hr/>
		<div class="mb-3">
			<h2>My Books:</h2>
			{% if my_books %}
				<div class="card-deck col-lg-10 col-sm-12 py-2 mx-auto">
				{% for object in my_books %}
					<div class="card col-sm-4 rounded">
					<div class="card-body">
						<a class="text-decoration-none text-dark card-title" href="{{ object.get_absolute_url }}" ><h5> {{ object.book.title }}</h5></a>
						<p class="card-subtitle mb-2 text-muted"> {{ object.book.author }}</p>
						<p class="card-text">{{ object.book.edition }} Edition</p>
						<p class="card-text">ISBN-13: {{ object.book.isbn }}</p>
						<p class="card-text">Price: ${{ object.price}}</p>
						<a href="{{ object.get_absolute_url }}" class="btn btn-primary">Details</a>
					</div>
					</div>
				{% endfor %}
				</div>
				<a class="btn btn-primary" href="{% url 'sellerlisting' %}">Sell Another Book</a>
			{% else %}
				<p>You have not listed any books yet.</p>
				<a class="btn btn-primary" href="{% url 'sellerlisting' %}">Sell A Book</a>
			{% endif %}
		</div>
		<hr/>
		<div class="mb-3">
			<h2>Suggestions:</h2>
			{% if left %}
				<div class="card-deck col-lg-10 col-sm-12 py-2 mx-auto">
				{% for object in left %}
					<div class="card col-sm-4 rounded">
					<div class="card-body">
						<a class="text-decoration-none text-dark card-title" href="{{ object.get_absolute_url }}" ><h5> {{ object.book.title }}</h5></a>
						<p class="card-subtitle mb-2 text-muted"> {{ object.book.author }}</p>
						<p class="card-text">{{ object.book.edition }} Edition</p>
						<p class="card-text">ISBN-13: {{ object.book.isbn }}</p>
						<p class="card-text">Price: ${{ object.price}}</p>
						<a href="{{ object.get_absolute_url }}" class="btn btn-primary">Details</a>
					</div>
					</div>
				{% endfor %}
				</div>
			{% else %}
				<p>You have no suggestions at the moment. Check back later for more.</p>
			{% endif %}
		</div>
		<hr/>
		<div class="mb-3">
			<h2>Your Cart:</h2>
			{% if cart %}
			
			<div class="card-deck col-lg-10 col-sm-12 py-2 mx-auto">
			{% for product in cart %}
					<div class="card col-sm-4 rounded">
					<div class="card-body">
					<h5 class="card-title"> {{ product.product.book.title }}</h5>
					<p class="card-subtitle mb-2 text-muted"> {{ product.product.book.author }}</p>
					<p class="card-text">{{ product.product.book.edition }} Edition</p>
					<p class="card-text">${{ product.price}} </p>
					<p class="card-text">ISBN-13: {{ product.product.book.isbn }}</p>
					<a href="{% url 'cart:itemclear' product.product.id%}" class="btn btn-primary mb-1">Remove From Cart</a>
					<a href = "{% url 'newconversation' product.product.id%}" class="btn btn-primary mb-1" >Contact Seller</a>
					</div>
				</div>

			{% endfor %}
			</div>
			
			{% else %}
			<p>Your cart is empty.</p>
			{% endif %} 
		</div>
		<hr/>
		{% if user.is_admin or user.is_superuser %}
		<div class="text-center my-2">
			<a class="btn btn-primary btn-lg" href="{% url 'admin' %}">Go to Admin Page</a>
		</div>

		{% endif %}
		<div class="text-center my-2">
			<a class="btn btn-primary btn-lg" href="{% url 'logout' %}">Log out</a>
		</div>

	{% else %}
		<meta http-equiv="refresh" content="time; URL=../login" />

	{% endif %}
</div>
{%endblock%}