cart/urls.py
from django.urls import path
from . import views

app_name = "cart"


urlpatterns = [
    path('cart/add/<uuid:id>/', views.cartadd, name='cartadd'),
    path('cart/item-clear/<uuid:id>/', views.itemclear, name='itemclear'),
    path('cart/cart-detail/',views.cartdetail, name='cartdetail'),

]

oasis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('pages.urls')),
    path('', include(('cart.urls', 'cart'), namespace='cart')),
    path('', RedirectView.as_view(url='pages/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models
import uuid # Required for unique listings
from django.forms import ModelForm
from django.urls import reverse
from pages.choices import *
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver


User = settings.AUTH_USER_MODEL




# Create your models here.

#class User(models.Model):
 #   email = models.EmailField(max_length=200)
 #   def __str__(self):
 #       return self.name


class Listing(models.Model):
    #fields
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='unique id for this listing')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User,
                        default = 1,
                        null = True,
                        on_delete = models.SET_NULL
                        )
    price= models.DecimalField(max_digits=10, decimal_places=2)
    hide_listing = models.BooleanField(default=False)
    times_reported = models.SmallIntegerField(default=0)
    report = models.ForeignKey('ReportListing',null = True, on_delete = models.SET_NULL)

    # not yet sure how users work - may want users not to be a model and instead use django default user handling
    # posted_by = models.ForeignKey('User', on_delete=models.SET_NULL,null=True)


    condition = models.CharField(
        max_length=1,
        choices=CONDITION,
        blank=True,
        default=1,
        help_text='Book condition',
    )
    # not yet sure yet how to handle images
    # image =

    class Meta:
        ordering = ['-date_added']

    # Methods
    def get_absolute_url(self):
        """Returns the url to access a particular instance of MyModelName."""
        return reverse('listings-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return f'{self.id} ({self.book.title})'

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    #if we decide to have a model for author:
    #author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    isbn = models.CharField('ISBN', max_length=13, unique=True, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    edition = models.CharField(max_length=5) #length here assumes no more than 999th edition -- seems like a reasonable assumption
    pub_year = models.SmallIntegerField()

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])


#message thread
class Conversation(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='unique id for this conversation')
    seller = models.ForeignKey(User,
                        related_name='seller',
                        default = 1,
                        null = True,
                        on_delete = models.SET_NULL
                        )
    buyer = models.ForeignKey(User,
                        related_name='buyer',
                        default = 2,
                        null = True,
                        on_delete = models.SET_NULL
            )
    report = models.ForeignKey('ReportListing',null = True, on_delete = models.SET_NULL)
    state = models.CharField(
        max_length=1,
        choices=STATUS,
        blank=True,
        default=0,
        help_text='Conversation status',
    )
    listing = models.ForeignKey(Listing, null = True, on_delete = models.SET_NULL)


class Message(models.Model):
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    sentby = models.ForeignKey(User,
                        default = 1,
                        null = True,
                        on_delete = models.SET_NULL
                        )
    conversation = models.ForeignKey(Conversation, default = 1, null=True, on_delete = models.SET_NULL)
    class Meta:
        ordering = ['-timestamp']

class ReportListing(models.Model):
    sent_by = models.ForeignKey(User, default = 1,
                        null = True,
                        on_delete = models.SET_NULL)
    date_reported = models.DateTimeField(auto_now_add=True)

class NumSearch(models.Model):
    count = models.IntegerField(default=0)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    buyer_rating = models.IntegerField(
        choices = RATINGS,
        default = 5,
    )
    seller_rating = models.IntegerField(
        choices = RATINGS,
        default = 5,
    )

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Photo(models.Model):
    uuid = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False,
    )
    created_at = models.DateTimeField(auto_now_add=True) 
    title = models.CharField(max_length=100)
    photo = models.FileField()

cart/views.py
from django.shortcuts import render, redirect
from pages.models import Listing
from django.contrib.auth.decorators import login_required
from cart.cart import Cart
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect



@login_required(login_url="/pages/login")
def cartadd(request, id):
    cart = Cart(request)
    product = Listing.objects.get(id=id)
    cart.add(product=product)
    return redirect("/cart/cart-detail/")


@login_required(login_url="/pages/login")
def itemclear(request, id):
    cart = Cart(request)
    product = Listing.objects.get(id=id)
    cart.remove(product)
    return redirect('/cart/cart-detail/')

@login_required(login_url="/pages/login")
def cartdetail(request):
    cart = Cart(request)
    products = []
    context = { 'cart': cart }
    context['products'] = products
    return render(request, 'cart_detail.html', context)
    #return render(request, 'cart_detail.html')

oasis/pages/templates/admin_view.html
{% extends 'base.html' %}

{%block content%}

{% if user.is_admin or user.is_superuser %}
<div class="col-lg-10 col-md-11 col-sm-12 mx-auto">
	<div class="text-center mb-3">
		<h1>Admin Page</h1>
		<p class="h2 text-muted">Welcome admin, {{user.username}}!</p>
	</div>
	<div class="mb-3">
		<h3 class="">Basic Metrics</h3>
		<p>There have been <strong>{{ num_books }}</strong> books put up for sale.</p>
		<p><strong>{{num_listings}}</strong> of those are still for sale.</p>
		<p>There are <strong>{{num_users}}</strong> users registered.</p>
		{% for num in searches %}
		<p>There have been <strong>{{num.count}}</strong> searches.</p>
		{% endfor %}
	</div>
	<hr/>
	<div class="mb-3">
		<h3>User Reports</h3>
		<div class="card-deck py-2 mx-auto">
			{% for object in report %}
			<div class="card col-sm-4 rounded">
				<div class="card-body">
					<h5 class="card-title"> {{ object.book.title }}</h5>
					<p class="card-subtitle mb-2 text-muted"> {{ object.book.author }}</p>
					<p class="card-text">{{ object.book.edition }} Edition</p>
					<p class="card-text">ISBN-13: {{ object.book.isbn }}</p>
					<p class="card-text">Price: ${{ object.price}}</p>
					<a href="{{ object.get_absolute_url }}" class="btn btn-primary">Details</a>
					<p class="card-text">Reporting Party: {{object.report.sent_by}}</p>
					<a href="{% url 'newuserconversation' object.report.sent_by.id %}" class="btn btn-primary">Message Reporter</a>
					<p class="card-text">Report Date: {{object.report.date_reported}}</p>
					<hr/>
					<a href="{% url 'removelisting' object.id %}" class="btn btn-primary mx-1 my-1">Remove Listing</a>
					<a href="{% url 'newuserconversation' object.user.id %}" class="btn btn-primary mx-1 my-1">Message Reported</a>
					<hr/>
					{% if object.user.is_active %}
					<a href="{% url 'inactivate_user' object.user.id %}" class="btn btn-primary my-2">Inactivate User</a>
					{% else %}
					<a href="{% url 'activate_user' object.user.id %}" class="btn btn-primary my-2">Activate User</a>
					{% endif %}
					<a href="{% url 'ban_user' object.user.id %}" class="btn btn-primary my-2">Ban User</a>
					<a href="{% url 'clearlisting' object.id %}" class="btn btn-primary my-2">Clear Report</a>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
	<hr/>
	<div class="mb-3">
		<h3>Users with Low Buyer Ratings</h3>
		<div class="card-deck py-2 mx-auto">
			{% for users in low_buyer %}
			<div class="card col-sm-4 rounded">
				<div class="card-body">
					<h5 class="card-title">User:  {{ users.user }}</h5>
					<p class="card-text">Rating: {{ users.buyer_rating }}</p>
					<br/>
					<a href="{% url 'newuserconversation' users.user.id %}" class="btn btn-primary">Message User</a>
					<br/>
					<br/>
					{% if users.user.is_active %}
					<a href="{% url 'inactivate_user' users.user.id %}" class="btn btn-primary mx-1 my-1">Inactivate User</a>
					{% else %}
					<a href="{% url 'activate_user' users.user.id %}" class="btn btn-primary mx-1 my-1">Activate User</a>
					{% endif %}
					<a href="{% url 'ban_user' users.user.id %}" class="btn btn-primary mx-1 my-1">Ban User</a>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
	<hr/>
	<div class="mb-3">
		<h3>Users with Low Seller Ratings</h3>
		<div class="card-deck py-2 mx-auto">
			{% for users in low_seller %}
			<div class="card col-sm-4 rounded">
				<div class="card-body">
					<h5 class="card-title">User:  {{ users.user }}</h5>
					<p class="card-text">Rating: {{ users.buyer_rating }}</p>
					<br/>
					<a href="{% url 'newuserconversation' users.user.id %}" class="btn btn-primary">Message User</a>
					<br/>
					<br/>
					{% if users.user.is_active %}
					<a href="{% url 'inactivate_user' users.user.id %}" class="btn btn-primary mx-1 my-1">Inactivate User</a>
					{% else %}
					<a href="{% url 'activate_user' users.user.id %}" class="btn btn-primary mx-1 my-1">Activate User</a>
					{% endif %}
					<a href="{% url 'ban_user' users.user.id %}" class="btn btn-primary mx-1 my-1">Ban User</a>
				</div>
			</div>
			<br/>
			{% endfor %}
		</div>
	</div>
	<hr/>
	<div class="text-center">
		<h4>Click below to access deeper database controls</h4>
		<a class="btn btn-primary btn-lg" href="{% url 'admin:index' %}">Account Management</a>
	</div>
	{% else %}
		<h1>You are not an Admin</h1>
		<p>Your account does not have permission to access this page. Click below to be taken back to the home page.</p>
		<a class="btn btn-lg btn-primary" href="{% url 'index' %}">Return Home</a>
	{% endif %}
</div>







{%endblock%}

oasis/pages/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Oasis</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- Add additional CSS -->
  <!-- to insert custom styling -->
  {% block styles %}
  {% endblock %}  
</head>
<body class="d-flex flex-column min-vh-100">
  {% block sidebar %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top mb-3">
    <!-- <div class="container-fluid"> -->
      <a class="navbar-brand" href="{% url 'index' %}">Oasis</a>
      {% if user.is_authenticated %}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="buyerServices" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Buyer Services
            </a>
            <div class="dropdown-menu" aria-labelledby="buyerServices">
              <a class="dropdown-item" href="{% url 'listings' %}">Listings</a>
              <a class="dropdown-item" href="{% url 'cart:cartdetail' %}">Cart</a>
              
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="sellerServices" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Seller Services
            </a>
            <div class="dropdown-menu" aria-labelledby="sellerServices">
              <a class="dropdown-item" href="{% url 'sellerlisting' %}">Sell A Book</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'messaging' %}">Messaging</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="profile" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Profile
            </a>
            <div class="dropdown-menu" aria-labelledby="profile">
              <a class="dropdown-item" href="{% url 'profile' %}">View Profile</a>
              {% if user.is_admin or user.is_superuser %}
              <a class="dropdown-item" href="{% url 'admin' %}">View Admin</a>
              {% endif %}
              <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" name="search" method="GET" action="{% url 'listings' %}"> 
          <input class="form-control mr-sm-2" type="text" name="q" placeholder="Search"/>
          <button class="btn btn-outline-light ml-2" type="submit">Search</button>
        </form> 
        
      </div>
      {% endif %}
      <!-- </div> -->
      
    </nav>
    {% endblock %}
    <div class="col-sm-12 col-lg-12 col-md-12 mb-3">
      {% block content %}{% endblock %}
    </div>
    
    {% block footer %}
    <footer class="page-footer font-small pt-2 bg-primary mt-auto">
      <div class="container-fluid text-center">
        <!-- Grid row -->
        <div class="row justify-content-center">
          <!-- Grid column -->
          <div class="col-md-2 mb-md-0 mb-3">
            <a class="text-decoration-none text-light" href="{% url 'index' %}"><h5>HOME</h5></a>
          </div>
          {% if user.is_authenticated %}
          <div class="col-md-2 mb-md-0 mb-3">
            <a class="text-decoration-none text-light" href="{% url 'listings' %}"><h5>BUY</h5></a>
          </div>
          <div class="col-md-2 mb-md-0 mb-3">
            <a class="text-decoration-none text-light" href="{% url 'sellerlisting' %}"><h5>SELL</h5></a>
          </div>
          <div class="col-md-2 mb-md-0 mb-3">
            <a class="text-decoration-none text-light" href="{% url 'messaging' %}"><h5>MESSAGES</h5></a>
          </div>
          <div class="col-md-2 mb-md-0 mb-3">
            <a class="text-decoration-none text-light" href="{% url 'profile' %}"><h5>PROFILE</h5></a>
          </div>
          {% endif %}
        </div>
        
      </footer>
      {% endblock %}
      
    </body>
    
    </html>

oasis/pages/templates/listings_view.html
{% extends "base.html" %}



{% block content %}
<!-- <h1>All Listings ({{ object_list|length }})</h1> -->

<div class="text-center">
  <h1>Search Results</h1>
</div>

<div class="row">
  <div class="col-12 col-lg-12 py-2 mx-auto">
    <form class="form-inline justify-content-center">
      <!-- <form name="search" method="GET" action="{% url 'listings' %}"> 
        <input type="text" name="q" placeholder="Search"/>
        <button class="btn btn-primary " type="submit">Search</button>
      </form> -->
    </form>
  </div>
</div>

<div class="row mx-auto">
  <div class="col-lg-2 ml-2 py-2 my-2">
    <button class="btn-lg btn-primary mb-2 w-100" type="button" data-toggle="collapse" data-target="#filters" aria-expanded="false" aria-controls="collapseExample">
      Filters
    </button>
    <form class="collapse" id="filters">
      <button class="btn btn-primary my-2 w-100">Apply</button>
      <div>
        <a class="btn btn-sm btn-outline-primary w-100 my-1" data-toggle="collapse" data-target="#titles" aria-expanded="false" aria-controls="titles">
          Title
        </a>
      </div>
      <div class="collapse" id="titles">
        <form class="col-md-5" method="get">
          <div class="input-group">
            <select name="type" class="selectpicker" multiple>
              {% for object in object_list %}
                <option>{{ object.book.title }}</option>
              {% endfor %}
            </select>    
            <span class="input-group-btn"><button class="btn btn-primary" type="submit">Apply</button></span>
          </div>
        </form>
      </div>
      <div>
        <a class="btn btn-sm btn-outline-primary w-100 my-1" data-toggle="collapse" data-target="#authors" aria-expanded="false" aria-controls="authors">
          Authors
        </a>
      </div>
      <div class="collapse" id="authors">
        {% for object in object_list %}
        <p>{{ object.book.author }}</p>
        {% endfor %}
      </div>
      <div>
        <a class="btn btn-sm btn-outline-primary w-100 my-1" data-toggle="collapse" data-target="#editions" aria-expanded="false" aria-controls="editions">
          Edition
        </a>
      </div>
      <div class="collapse" id="editions">
        Distinct Edition Buttons
      </div>
      <div>
        <a class="btn btn-sm btn-outline-primary w-100 my-1" data-toggle="collapse" data-target="#conditions" aria-expanded="false" aria-controls="conditions">
          Condition
        </a>
      </div>
      <div class="collapse" id="conditions">
        <form>
          {{ form.condition_field }}
          <input type="submit" class="btn btn-primary" value="Apply">
        </form>
      </div>
    </form>
  </div>
  {% if object_list %}
  <div class="col-lg-9 col-md-10 col-sm-12 mx-auto">
    
    {% for object in object_list %}
    {% if object.hide_listing is False %}
    <!-- will need to adjust to create grid with fixed num of columns  -->
    <!-- <div class="col-sm-4"> -->
      <!-- <a href="{{ object.get_absolute_url }}">{{ object.book.title }}</a> {{object.book.author}} -->
      <div class="row border rounded mb-3 py-1" style="min-height: 200px;">
        
        <div class="col-lg-2 col-md-2 col-sm-12 mx-2 my-auto" style="min-height: 50px;">
          Cover image of the book
        </div>
        
        <div class="col-lg-4 col-md-5 col-sm-12 my-auto mr-auto">
          <a class="text-decoration-none text-dark" href="{{ object.get_absolute_url }}" ><h4> {{ object.book.title }}</h4></a>
          <p class="text-muted"> {{ object.book.author }}</p>
          <p><strong>Edition:</strong> {{ object.book.edition }}</p>
          <p><strong>ISBN-13:</strong> {{ object.book.isbn }}</p>
          <p><strong>Sold by:</strong> {{ object.user.username }} </p>
        </div>
        
        <div class="my-auto col-lg-4 col-md-3 col-sm-12">
          <p><strong>Condition:</strong> {{object.get_condition_display}}</p> 
          <p><strong>Price:</strong> ${{ object.price}}</p>
          <a href="{{ object.get_absolute_url }}" class="btn btn-primary w-100 mb-3">Details</a>
        </div>
        
      </div>
      {% endif %}
      {% endfor %}
    </div>
  </div>
  
  <!-- <ul>
    {% for object in object_list %}
    <li>
      <a href="{{ object.get_absolute_url }}">{{ object.book.title }}</a> {{object.book.author}}
    </li>
    {% endfor %}
  </ul> -->
  {% else %}
  <p>There are no current listings.</p>
  {% endif %} 
</div>
{% endblock %}

oasis/pages/templates/profile.html
{% extends 'base.html' %}

{%block content%}
<div class="col-lg-10 col-md-11 col-sm-12 mx-auto">
	{% if user.is_authenticated %}

		<h1 class="text-center my-3">Welcome to your profile, {{user.username}}!</h1>

		<div class="text-center my-3">
			<p class="mb-2"><strong>Buyer Rating:</strong> {{user.profile.buyer_rating}}</p>
			<p><strong>Seller Rating:</strong> {{user.profile.seller_rating}}</p>
		</div>
		<hr/>
		<div class="mb-3">
			<h2>My Books:</h2>
			{% if my_books %}
				<div class="card-deck col-lg-10 col-sm-12 py-2 mx-auto">
				{% for object in my_books %}
					<div class="card col-sm-4 rounded">
					<div class="card-body">
						<a class="text-decoration-none text-dark card-title" href="{{ object.get_absolute_url }}" ><h5> {{ object.book.title }}</h5></a>
						<p class="card-subtitle mb-2 text-muted"> {{ object.book.author }}</p>
						<p class="card-text">{{ object.book.edition }} Edition</p>
						<p class="card-text">ISBN-13: {{ object.book.isbn }}</p>
						<p class="card-text">Price: ${{ object.price}}</p>
						<a href="{{ object.get_absolute_url }}" class="btn btn-primary">Details</a>
					</div>
					</div>
				{% endfor %}
				</div>
				<a class="btn btn-primary" href="{% url 'sellerlisting' %}">Sell Another Book</a>
			{% else %}
				<p>You have not listed any books yet.</p>
				<a class="btn btn-primary" href="{% url 'sellerlisting' %}">Sell A Book</a>
			{% endif %}
		</div>
		<hr/>
		<div class="mb-3">
			<h2>Suggestions:</h2>
			{% if left %}
				<div class="card-deck col-lg-10 col-sm-12 py-2 mx-auto">
				{% for object in left %}
					<div class="card col-sm-4 rounded">
					<div class="card-body">
						<a class="text-decoration-none text-dark card-title" href="{{ object.get_absolute_url }}" ><h5> {{ object.book.title }}</h5></a>
						<p class="card-subtitle mb-2 text-muted"> {{ object.book.author }}</p>
						<p class="card-text">{{ object.book.edition }} Edition</p>
						<p class="card-text">ISBN-13: {{ object.book.isbn }}</p>
						<p class="card-text">Price: ${{ object.price}}</p>
						<a href="{{ object.get_absolute_url }}" class="btn btn-primary">Details</a>
					</div>
					</div>
				{% endfor %}
				</div>
			{% else %}
				<p>You have no suggestions at the moment. Check back later for more.</p>
			{% endif %}
		</div>
		<hr/>
		<div class="mb-3">
			<h2>Your Cart:</h2>
			{% if cart %}
			
			<div class="card-deck col-lg-10 col-sm-12 py-2 mx-auto">
			{% for product in cart %}
					<div class="card col-sm-4 rounded">
					<div class="card-body">
					<h5 class="card-title"> {{ product.product.book.title }}</h5>
					<p class="card-subtitle mb-2 text-muted"> {{ product.product.book.author }}</p>
					<p class="card-text">{{ product.product.book.edition }} Edition</p>
					<p class="card-text">${{ product.price}} </p>
					<p class="card-text">ISBN-13: {{ product.product.book.isbn }}</p>
					<a href="{% url 'cart:itemclear' product.product.id%}" class="btn btn-primary mb-1">Remove From Cart</a>
					<a href = "{% url 'newconversation' product.product.id%}" class="btn btn-primary mt-1" >Contact Seller</a>
					</div>
				</div>

			{% endfor %}
			</div>
			
			{% else %}
			<p>Your cart is empty.</p>
			{% endif %} 
		</div>
		<hr/>
		{% if user.is_admin or user.is_superuser %}
		<div class="text-center my-2">
			<a class="btn btn-primary btn-lg" href="{% url 'admin' %}">Go to Admin Page</a>
		</div>

		{% endif %}
		<div class="text-center my-2">
			<a class="btn btn-primary btn-lg" href="{% url 'logout' %}">Log out</a>
		</div>

	{% else %}
		<meta http-equiv="refresh" content="time; URL=../login" />

	{% endif %}
</div>
{%endblock%}